name: tweet_scheduler

on:
  schedule:
    - cron: '*/15 * * * *'
      # Runs every 15 minutes to get latest news

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ENV
        env:
          OAUTH_CONSUMER_KEY: ${{ secrets.OAUTH_CONSUMER_KEY}}
          OAUTH_CONSUMER_SECRET: ${{ secrets.OAUTH_CONSUMER_SECRET}}
          OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN}}
          OAUTH_TOKEN_SECRET: ${{ secrets.OAUTH_TOKEN_SECRET}}
        uses: actions/checkout@v1
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.0.4'
      - name: Build
        uses: julia-actions/julia-buildpkg@master
      - name: Run
        run: julia --project src/script.jl
